"""LunaLink AFS subpackage — Augmented Forward Signal implementation."""

from lunalink.afs.signal import (
    BCH_CODEWORD_LENGTH,
    EPOCHS_PER_FRAME,
    FRAME_DURATION_S,
    FRAME_LENGTH,
    INTERIM_ASSIGNMENT_MAX_PRN,
    IQ_SAMPLES_PER_EPOCH,
    IQ_UPSAMPLE_FACTOR,
    PAYLOAD_LENGTH,
    SB1_LENGTH,
    SECONDARY_CODE_COUNT,
    SECONDARY_CODE_LENGTH,
    SYMBOL_RATE,
    SYNC_LENGTH,
    TERTIARY_CODE_LENGTH,
    FrameStatus,
    bch_encode,
    frame_build_partial,
    modulate_i,
    modulate_q,
    multiplex_iq,
    prn_code,
    tiered_code_epoch,
    tiered_code_epoch_assigned,
    weil1500_code,
    weil10230_code,
)

__all__ = [
    "bch_encode",
    "frame_build_partial",
    "BCH_CODEWORD_LENGTH",
    "FRAME_LENGTH",
    "SYNC_LENGTH",
    "SB1_LENGTH",
    "PAYLOAD_LENGTH",
    "SYMBOL_RATE",
    "FRAME_DURATION_S",
    "prn_code",
    "weil10230_code",
    "weil1500_code",
    "modulate_i",
    "modulate_q",
    "multiplex_iq",
    "tiered_code_epoch",
    "tiered_code_epoch_assigned",
    "EPOCHS_PER_FRAME",
    "SECONDARY_CODE_LENGTH",
    "SECONDARY_CODE_COUNT",
    "INTERIM_ASSIGNMENT_MAX_PRN",
    "TERTIARY_CODE_LENGTH",
    "IQ_UPSAMPLE_FACTOR",
    "IQ_SAMPLES_PER_EPOCH",
    "FrameStatus",
]
